# Generated by Django 5.0.4 on 2024-05-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0002_customer_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contactno',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='emailaddress',
            field=models.EmailField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(max_length=50),
        ),
    ]
